### ISSUE TITLE
References to PATRIC in the installation document

### ISSUE THREAD

**Issue by jwokaty** [BV-BRC/BV-BRC-Docs#76]
On the installation page at https://github.com/BV-BRC/BV-BRC-Docs/blob/master/docroot/cli_tutorial/cli_installation.rst, there are references to `patric-cli-1.040.deb`

```
curl -O -L https://github.com/BV-BRC/BV-BRC-CLI/releases/download/1.040/bvbrc-cli-1.040.deb
sudo dpkg -i patric-cli-1.040.deb
sudo sudo apt-get -f install
```
and later

```
sudo gdebi patric-cli-1.040.deb
```

Should these be `bvbrc-cli-1.040.deb`?

**Comment by chris-c-thomas** [comment]
@jwokaty that's correct, thank you for pointing that out for us.

It's a leftover from the old naming convention. You'll want to use `sudo dpkg -i bvbrc-cli-1.040.deb` as you won't have a file with the patric name after downloading.
